import { readFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";
import { healthFactor, quoteSeize, quoteShares, quoteWithdraw } from "./math.js";
import { extractCode } from "./tx.js";
import { SCALE } from "./types.js";

// Load the SAME fixtures the contracts are tested against
// (tests/fixtures/golden.json, generated by golden_gen.py). The SDK's pure
// previews must reproduce every vector exactly — this makes drift impossible.
const here = dirname(fileURLToPath(import.meta.url));
type Vec = { name: string; [k: string]: number | string };
const golden = JSON.parse(
  readFileSync(resolve(here, "../../../tests/fixtures/golden.json"), "utf8"),
) as { vault: Vec[]; pool: Vec[] };
const B = (n: number | string | undefined): bigint => BigInt(n ?? 0);

describe("quoteShares/quoteWithdraw — golden vault vectors", () => {
  for (const v of golden.vault) {
    it(v.name, () => {
      if ("expect_shares" in v) {
        expect(quoteShares(B(v.deposit), B(v.nav), B(v.bal_before), B(v.total_shares_before))).toBe(
          B(v.expect_shares),
        );
      } else {
        expect(quoteWithdraw(B(v.shares), B(v.nav), B(v.balance_after_rebase), B(v.shares))).toBe(
          B(v.expect_withdraw),
        );
      }
    });
  }
});

describe("healthFactor / quoteSeize — golden pool vectors", () => {
  for (const p of golden.pool) {
    it(p.name, () => {
      if ("expect_hf" in p) {
        expect(healthFactor(B(p.shares), B(p.debt), B(p.share_price))).toBe(B(p.expect_hf));
      } else {
        expect(quoteSeize(B(p.repay), B(p.share_price))).toBe(B(p.expect_seize));
      }
    });
  }
});

describe("edge cases", () => {
  it("quoteShares rejects zero/negative", () => {
    expect(quoteShares(0n, SCALE, 0n, 0n)).toBe(0n);
    expect(quoteShares(-5n, SCALE, 0n, 0n)).toBe(0n);
  });
  it("quoteWithdraw clamps to the vault balance", () => {
    expect(quoteWithdraw(10n ** 12n, SCALE, 5n, 100n)).toBe(5n);
  });
  it("healthFactor is null when debt-free", () => {
    expect(healthFactor(1n, 0n, SCALE)).toBeNull();
  });
  it("quoteSeize is zero for non-positive inputs", () => {
    expect(quoteSeize(0n, SCALE)).toBe(0n);
    expect(quoteSeize(100n, 0n)).toBe(0n);
  });
});

describe("extractCode", () => {
  it("pulls the contract error number", () => {
    expect(extractCode("HostError: Error(Contract, #6)")).toBe(6);
    expect(extractCode("transaction failed: FAILED")).toBeNull();
  });
});
