#!/usr/bin/env bash
# gen_app_env.sh — project deploy.env into app/.env.local (VITE_-prefixed) so the
# dApp reads the live testnet deployment. Run after setup_testnet.sh (or `just app`).
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

[ -f deploy.env ] || { echo "deploy.env not found — run scripts/setup_testnet.sh first"; exit 1; }
# shellcheck disable=SC1091
source deploy.env

OUT="app/.env.local"
cat > "$OUT" <<EOF
# Generated by scripts/gen_app_env.sh from deploy.env — do NOT commit (gitignored).
VITE_RPC_URL=${STELLAR_RPC_URL:-https://soroban-testnet.stellar.org}
VITE_NETWORK_PASSPHRASE=Test SDF Network ; September 2015
VITE_EXPLORER_BASE=https://stellar.expert/explorer/testnet
VITE_VAULT_FACTORY=$VAULT_FACTORY
VITE_VAULT_LEOD=$VAULT
VITE_ORACLE_ADAPTER=$ORACLE_ADAPTER
VITE_MOCK_ORACLE=$MOCK_ORACLE
VITE_MINI_POOL=$MINI_POOL
VITE_LEOD_SAC=$LEOD_SAC
VITE_USDC_SAC=$USDC_SAC
VITE_LEOD_ASSET_ID=LEOD
VITE_DEMO_MODE=true
VITE_DEMO_ISSUER_SK=${DEMO_ISSUER_SK:-}
VITE_DEMO_ADMIN_SK=${DEMO_ADMIN_SK:-}
VITE_DEMO_USER_SK=${DEMO_USER_SK:-}
VITE_DEMO_LIQUIDATOR_SK=${DEMO_LIQUIDATOR_SK:-}
VITE_DEMO_RANDO_SK=${DEMO_RANDO_SK:-}
EOF
echo "wrote $OUT"
