#!/usr/bin/env python3
"""Golden-vector generator for the Leontief vault + mini-pool (prompt C8).

These vectors are the reproducibility / audit-bank hand-off: the Rust loaders in
tests/tests/golden.rs drive the *real* contracts and assert byte-for-byte
equality with this file. The math here mirrors the contracts' i128 checked
integer arithmetic EXACTLY (floor via Python //, explicit ceil), so Python's
arbitrary-precision ints reproduce on-chain results with zero drift. `Decimal`
(precision 50) documents the human-readable NAV levels.

Run: `python3 tests/fixtures/golden_gen.py` (or `just golden`). Commit the diff
deliberately - a change here is a change to the contracts' expected behavior.
"""
from __future__ import annotations

import json
from decimal import Decimal, getcontext
from pathlib import Path

getcontext().prec = 50

SCALE = 10**12
VIRT = 10**3
BPS = 10_000
LTV_BPS = 8_000
LIQ_THRESHOLD_BPS = 8_500
LIQ_BONUS_BPS = 500

NAV_1_0000 = SCALE
NAV_1_0209 = int(SCALE * Decimal("1.0209"))
NAV_1_0409 = int(SCALE * Decimal("1.0409"))


def value_of(balance: int, nav: int) -> int:
    return balance * nav // SCALE


def mint_shares(received: int, nav: int, bal_before: int, total_shares: int) -> int:
    v_before = value_of(bal_before, nav)
    value_in = received * nav // SCALE
    return value_in * (total_shares + VIRT) // (v_before + VIRT)


def redeem_amount(shares: int, nav: int, balance: int, total_shares: int) -> int:
    v = value_of(balance, nav)
    value_out = shares * (v + VIRT) // (total_shares + VIRT)
    return min(value_out * SCALE // nav, balance)


def share_price(balance: int, nav: int, total_shares: int) -> int:
    v = value_of(balance, nav)
    return (v + VIRT) * SCALE // (total_shares + VIRT)


def coll_value(shares: int, sp: int) -> int:
    return shares * sp // SCALE


def health_factor(shares: int, sp: int, debt: int) -> int:
    if debt == 0:
        return 2**127 - 1
    cv = coll_value(shares, sp)
    adjusted = cv * LIQ_THRESHOLD_BPS // BPS
    return adjusted * SCALE // debt


def seize_shares(repay: int, sp: int) -> int:
    def ceil_div(a: int, b: int) -> int:
        return -(-a // b)
    bonus_value = ceil_div(repay * (BPS + LIQ_BONUS_BPS), BPS)
    return ceil_div(bonus_value * SCALE, sp)


def vault_vectors() -> list:
    out = []
    dep1 = 100_0000000
    s1 = mint_shares(dep1, NAV_1_0209, 0, 0)
    out.append({"name": "first_deposit_nav_1_0209", "nav": NAV_1_0209,
                "bal_before": 0, "total_shares_before": 0,
                "deposit": dep1, "expect_shares": s1})

    dep2 = 100_0000000
    s2 = mint_shares(dep2, NAV_1_0409, dep1, s1)
    out.append({"name": "second_depositor_after_nav_rise", "nav": NAV_1_0409,
                "bal_before": dep1, "total_shares_before": s1,
                "deposit": dep2, "expect_shares": s2})

    dep3 = 100_0000000
    s3 = mint_shares(dep3, NAV_1_0000, 0, 0)
    rebased = dep3 + dep3 * 19 // 10_000
    w3 = redeem_amount(s3, NAV_1_0000, rebased, s3)
    out.append({"name": "rebase_then_withdraw_all", "nav": NAV_1_0000,
                "deposit": dep3, "shares": s3,
                "balance_after_rebase": rebased, "expect_withdraw": w3})

    sd = mint_shares(1, NAV_1_0209, 0, 0)
    out.append({"name": "dust_deposit_one_stroop", "nav": NAV_1_0209,
                "bal_before": 0, "total_shares_before": 0,
                "deposit": 1, "expect_shares": sd})

    cap = 500_0000000
    sc = mint_shares(cap, NAV_1_0000, 0, 0)
    out.append({"name": "cap_edge_deposit", "nav": NAV_1_0000, "cap": cap,
                "deposit": cap, "expect_shares": sc})
    return out


def pool_vectors() -> list:
    out = []
    shares = 500_0000000
    debt = 300_0000000
    for label, nav in [("nav_1_0000", NAV_1_0000),
                        ("nav_1_0200", int(SCALE * Decimal("1.02"))),
                        ("nav_0_9400", int(SCALE * Decimal("0.94")))]:
        sp = share_price(shares, nav, shares)
        out.append({"name": "hf_" + label, "nav": nav, "shares": shares,
                    "debt": debt, "share_price": sp,
                    "coll_value": coll_value(shares, sp),
                    "expect_hf": health_factor(shares, sp, debt)})

    sp_crashed = share_price(shares, int(SCALE * Decimal("0.90")), shares)
    for repay in [50_0000000, 100_0000000, 200_0000000]:
        out.append({"name": "seize_repay_" + str(repay),
                    "share_price": sp_crashed, "repay": repay,
                    "expect_seize": seize_shares(repay, sp_crashed)})
    return out


def main() -> None:
    doc = {
        "_comment": "Generated by tests/fixtures/golden_gen.py - do not hand-edit.",
        "constants": {"SCALE": SCALE, "VIRT": VIRT, "BPS": BPS,
                      "LTV_BPS": LTV_BPS, "LIQ_THRESHOLD_BPS": LIQ_THRESHOLD_BPS,
                      "LIQ_BONUS_BPS": LIQ_BONUS_BPS},
        "vault": vault_vectors(),
        "pool": pool_vectors(),
    }
    path = Path(__file__).with_name("golden.json")
    path.write_text(json.dumps(doc, indent=2) + "\n")
    print("wrote", path, "-", len(doc["vault"]), "vault +", len(doc["pool"]), "pool vectors")


if __name__ == "__main__":
    main()
